[package]
name = "inferdf"
version = "0.1.0"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2021"

[dependencies]
log = "0.4.17"
rdf-types = { version = "0.12.18", features = ["meta"] }
iref = { version = "2.2.3", features = ["hashbrown"] }
static-iref = "2.0.0"
derivative = "2.2.0"
locspan = { version = "0.7.13", features = ["reporting"] }
langtag = "0.3.2"
slab = "0.4.7"
hashbrown = "0.13.2"
async-trait = "0.1.64"
futures = "0.3.26"