[package]
name = "inferdf"
version = "0.1.0"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2021"

[dependencies]
log = "0.4.17"
# rdf-types = { version = "0.14.9", features = ["meta", "contextual", "serde"] }
rdf-types = { git = "https://github.com/timothee-haudebourg/rdf-types.git", rev = "870c0d6", features = ["meta", "contextual", "serde"] }
iref = { version = "2.2.3", features = ["hashbrown", "serde"] }
static-iref = "2.0.0"
derivative = "2.2.0"
locspan = { version = "0.7.13", features = ["reporting"] }
langtag = { version = "0.3.3", features = ["serde"] }
slab = "0.4.7"
hashbrown = "0.13.2"
async-trait = "0.1.64"
futures = "0.3.26"
im = "15.1.0"
contextual = "0.1.6"
serde = { version = "1.0", features = ["derive"] }

clap = { version = "4.0", features = ["derive"] }
# nquads-syntax = "0.12.0"
nquads-syntax = { git = "https://github.com/timothee-haudebourg/nquads-syntax.git", rev = "b53c5dc" }
stderrlog = "0.5.4"
ron = "0.8"