[workspace]
members = [
	"core",
	"storage",
	"inference",
	"cli"
]

[workspace.package]
version = "0.1.0"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2021"

[workspace.dependencies]
inferdf-core = { path = "core" }
inferdf-inference = { path = "inference" }
inferdf-storage = { path = "storage" }

log = "0.4.17"
# rdf-types = { version = "0.14.9", features = ["meta", "contextual", "serde"] }
rdf-types = { git = "https://github.com/timothee-haudebourg/rdf-types.git", rev = "870c0d6", features = ["meta", "contextual", "serde"] }
nquads-syntax = { git = "https://github.com/timothee-haudebourg/nquads-syntax.git", rev = "b53c5dc" }
iref = { version = "2.2.3", features = ["hashbrown", "serde"] }
langtag = "0.3.3"
derivative = "2.2.0"
hashbrown = "0.13.2"
contextual = "0.1.6"
locspan = { version = "0.7.13", features = ["reporting"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.40"